/* Recipe:
  id:
  name:
  category: [category: [reference to Category], name?]
  ingredients: [{ingredient: [reference to Ingredient], name?, quantity?}]
  steps: []

* - Steps are embedded because they are less likely to be shared between recipes. 
  - A set of steps is unique to each recipe and usually does not change.
  - Usually a recipe query will return the steps along with the recipe name.


* - Ingredients and categories are referenced to avoid duplication and inconsistency. 
  - They are not embedded because they are likely to be shared between recipes and 
  are likely to be updated.
  - Additional fields can be added to the Ingredient and Category schemas to allow
  for more detailed information to be stored.
  - Ingredient and category names are stored in the recipe schema to allow for
  easy access to the names without needing to query the Ingredient and Category. */

import is from 'joi';
import { ObjectId } from 'mongodb';

// Custom Joi extension to validate MongoDB ObjectId
const mongo = is.extend((joi) => ({
  type: 'objectId',
  messages: {
    'objectId.base': '"{#label}" must be a valid ObjectId',
  },
  validate(value, helpers) {
    if (!ObjectId.isValid(value)) {
      return { value, errors: helpers.error('objectId.base') };
    }
    return { value };
  },
}));

//document IDs optional because it will be generated by mongodb

const categorySchema = is.object({
  _id: mongo.objectId().optional(),
  name: is.string().required(),
  description: is.string().optional(),
  region: is.string().optional(),
});

const ingredientSchema = is.object({
  _id: mongo.objectId().optional(),
  name: is.string().required(),
  description: is.string().optional(),
  alternatives: is.array().items(is.string()).optional(),
});

const recipeIngredientSchema = is.object({
  ingredient_id: mongo.objectId().required(),
  name: is.string().optional(), //frequently queried with recipe
  quantity: is.number().greater(0).optional(),
});

const recipeCategorySchema = is.object({
  category_id: mongo.objectId().required(),
  name: is.string().optional(), //frequently queried with recipe
});

const recipeSchema = is.object({
  _id: mongo.objectId().optional(),
  name: is.string().required(),
  categories: is.array().items(recipeCategorySchema).optional(),
  ingredients: is.array().items(recipeIngredientSchema).required(),
  steps: is.array().items(is.string()).required(),
});

export {
  categorySchema,
  ingredientSchema,
  recipeSchema,
  recipeCategorySchema,
  recipeIngredientSchema,
};
